version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  eureka-service:
    image: eureka-service
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    ports:
      - "8888:8888"
    restart: always
  gateway-service:
    image: gateway-service
    ports:
      - "8080:8080"
    restart: always
  catalog-service:
    image: catalog-service
    ports:
      - "8081:8081"
    restart: always
  movie-service:
    image: movie-service
    ports:
      - "8082:8082"
    restart: always
  serie-service:
    image: serie-service
    ports:
      - "8083:8083"
    restart: always
volumes: 
  data: { }
networks: 
  default:
    name: catalog_network