info:
  app:
    description: config-server
    name: ${spring.application.name}
    version: 1.2.0

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: circuitbreakers,circuitbreakerevents,health,info,metrics,ratelimiters

resilience4j:
  circuitbreaker:
    instances:
      moviesByGenre:
        allowHealthIndicatorToFail: false 
        automaticTransitionFromOpenToHalfOpenEnabled: true 
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED 
        waitDurationInOpenState: 15000
      seriesByGenre:
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 15000
  retry:
    instances:
      moviesByGenre:
        maxAttempts: 3 
        retryExceptions:
          - feign.FeignException$InternalServerError
          - feign.FeignException$ServiceUnavailable
       
        waitDuration: 1000 
      seriesByGenre:
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
          - feign.FeignException$ServiceUnavailable
        waitDuration: 1000

server:
  port: 8081