info:
  app:
    description: movie-service
    name: ${spring.application.name}
    version: 1.2.0

server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: pe
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: pe
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      data-locations: classpath:movie-service.sql