eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10

info:
  app:
    description: Config Server registerd in Eureka Server
    name: config-service
    version: 1.0.0

server:
  port: ${PORT:8888}

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          searchPaths: config
          uri: https://github.com/dionseid/movies-and-series-catalog-msa
